### ISSUE TITLE
Update readmes / descriptions of core spec / org / key repos to be more welcoming

### ISSUE THREAD

**Issue by cholmes** [fiboa/specification#18]
Ahead of an announcement we should be sure that we explain a bit more about the project to new users. Matthias has made a great start on this, but a few more things would be good to have:

- [x] Update [fiboa org readme](https://github.com/fiboa/.github/edit/main/profile/README.md) so it's a great landing page for the project. It should include a [clear mission statement](https://producingoss.com/en/getting-started.html#mission-statement), key [features](https://producingoss.com/en/getting-started.html#features-and-requirements), development status, license info, communication options (slack, zoom meeting, etc).
- [x] Update spec readme, to include at least a subset of the above, and to make clear the status of the spec and more general readme info for people to get a sense of things.
- [x] Update repo 'descriptions' - most repos in Fiboa right now have no 'about'. They should ideally include those, and any other good meta information.
- [x] Update other key readmes - check to be sure the most prominent readmes are all in good shape (validator, cli, ai extension, etc)
- [ ] Make sure instructions at top level are all in line with the way we want people to work.

**Comment by m-mohr** [comment]
@cholmes What is meant with "Make sure instructions at top level are all in line with the way we want people to work."?

**Comment by m-mohr** [comment]
Closing for now, let me know if you think there's more to do @cholmes
